### ISSUE TITLE
const class QString’ has no member named ‘front’ and has no member named ‘back’

### ISSUE THREAD

**Issue by jucamo8311** [pawelsalawa/sqlitestudio#3326]
### Details
Hi I'm trying to compile the source code that i got from Github but I noticed a compile error
### Steps to reproduce
Get the source code from 
``
git clone https://github.com/pawelsalawa/sqlitestudio.git sqlitestudio
``
When I execute the command 
./compile.sh /home/jucamo/Documents/Apps/Qt/5.9.5/gcc_64/bin/qmake
I see in the output 
``
../../../SQLiteStudio3/guiSQLiteStudio/datagrid/sqlqueryview.cpp:599:23: error: ‘const class QString’ has no member named ‘front’
             if ((cell.front().isSpace() || cell.back().isSpace()) && !trimOnPasteAsked)
                       ^~~~~
../../../SQLiteStudio3/guiSQLiteStudio/datagrid/sqlqueryview.cpp:599:49: error: ‘const class QString’ has no member named ‘back’
             if ((cell.front().isSpace() || cell.back().isSpace()) && !trimOnPasteAsked)
``
Looking in the docs of QT , these two functions were included in qt 5.10, so my guest is that unless you have qt version 5.10 its not going to compile successfully
### Operating system
Kubuntu 18.04

### SQLiteStudio version
The last code from git

**Comment by josephpaul0** [comment]
Same problem on Ubuntu 16.04 with QT 5.5.1
Please try to keep compatibility with Ubuntu LTS releases until EOL , if possible ;)
I know this is not always easy to maintain compatibility with "old" distributions.
I would be ready to donate money in order to have that kind of guarantee.
By the way, Paweł Salawa, sqlitestudio is great ! Keep up the good work !
Thank you.
