### ISSUE TITLE
[Feature Request] Add GTK+ style

### ISSUE THREAD

**Issue by jEsuSdA** [pawelsalawa/sqlitestudio#3441]
### Details
Hi!
I love SqliteStudio but it does not integrates very well with my Linux Desktop.
There are only two styles and all of them does not fix very well with other apps, so, please, could you add the GTK+ style into SqliteStudio?

Thanks a lot.

### Steps to reproduce

![imagen](https://user-images.githubusercontent.com/5833446/47519898-f9a38900-d88e-11e8-8bae-444a769136ca.png)

### Operating system
Debian GNU/Linux (XFCE Desktop)

### SQLiteStudio version
V 3.2.0

**Comment by pawelsalawa** [comment]
I think Gtk+ theme for Qt requires Gtk dependency to be fulfilled and it's not distributed by default with Qt (wherease SQLiteStudio is distributed with the default Qt distribution from qt.io). Such style would have to be linked against exactly same Gtk+ library you have in the system to make it fit to your current Gtk+ look&feel.

I assume you're using binaries from SQLiteStudio homepage. How about Debian dedicated packages? Aren't there any? I'm asking, because these would be using Qt that is provided with Debian and I believe this Qt has Gtk+ theme (but I may be wrong).

**Comment by jEsuSdA** [comment]
Hi, @pawelsalawa .

I'm using the binaries from SQLiteStudio homepage because there are no Debian dedicated packages. :_(

I requested Debian SQliteStudio to be added, but I don't know if this is going to happen anytime.

By the way, GTK+ style for QT is based upon GTK2 (who is not going to be changed a lot, cause the GTK3 version is the main one nowadays), so I think all the linux people has the same GTK2 libraries version. Maybe this can help you to try to add this style.

What do you think about?

**Comment by pawelsalawa** [comment]
To use the GTK theme, SQLiteStudio has to be linked with Qt, which has GTK style installed (and to install/compile it, you need to compile Qt with GTK being in your system at compile time). Because of that, it's not possible to provide out-of-the-box GTK theme in packages available at sqlitestudio.pl.

Still, it is possible to have GTK style if SQLiteStudio is built against Qt from the Linux distribution that you are using. Therefore to use GTK style, you need a distribution package, built specifically for your distribution (Debian, Ubuntu, RHEL, ...).

Given above, having the style depends on how the package is built and will be available if it's built against distribution's Qt and the GTK plugin is installed in distribution's Qt.

Nothing more to do with SQLiteStudio itself.
