### ISSUE TITLE
Windows 10 Sticky Tooltip

### ISSUE THREAD

**Issue by sonerb** [pawelsalawa/sqlitestudio#3468]
### Details
Rows tooltip not hide after cell mouseout.

### Steps to reproduce
When I hover a cell showing a tooltip and not hide a long time.

### Operating system
Windows 10 x64 (1709) 

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment]
This behavior is controlled by Qt (if not by Windows itself).

The tooltip will disappear if you:

1. move mouse out of the grid area (not to empty space of grid, but completely out of the data view frame)
2. move mouse off the cell quickly (not slowly) and by decent distance (not like 5cm, but 10 or more)

I believe intention behind this behavior (to keep the tooltip if you move slowly, not far and within the grid) was to not hide hint only because user moved the mouse a little bit, unintentionally. It's still pretty easy to hide the hint - move mouse away further/faster.
