### ISSUE TITLE
Suspicious Application

### ISSUE THREAD

**Issue by rrandor1** [pawelsalawa/sqlitestudio#3509]
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by rrandor1** [comment]
When I start Sqlite Studio I get the following message: 

Suspicious process “SQLiteStudio”! The process has no code signature. This means that the developer is anonymous and their real-life identity cannot be determined.
Suspicious process “UpdateSQLiteStudio”! The process has no code signature. This means that the developer is anonymous and their real-life identity cannot be determined.

Also being somewhat of a newbie I am concerned about the Magellan issue.  SS runs sqlite 3.22. Whereas the Magellan bug is avoided if FTS3 is not active or Sqlite 3.27 is installed. I cant tell if SS meets the first criteria.   
BTW, is there a way to search an entire drive to see where sqlite is installed and what versions are being run?   
I tried out many different sqlite managers and yours seemed to be the best. I flushed the rest. I am a former Visual FoxPro programmer. Curses on MS! That was the best relational database, but if I have to make do with sqlite, yours is the best of the bunch.

**Comment by pawelsalawa** [comment]
Ad 1) The warning you're seeing is quite common and it means that the executable is not signed by Microsoft's (paid annualy) certificate. You can just uncheck "show this warning every time when I run this application" at the bottom of the warning dialog and you will no longer be bothered with this.

Ad 2) As for the Magellan bug - there is nothing to worry about in case of applications like SQLiteStudio. This application is designed to execute whatever SQL you wish to, but it executes only user's input. It's not internet browser, it's not running code from remote hosts. It's a local application, therefore there is no risk of someone exploiting this bug.

The bug relates only to browsers (such as Chromium/Chrome) or to Android, because millions of applications can use SQLite in Android and some may be malicious.

In case of SQLiteStudio only you, the user of the application can execute SQL in the SQLite used by SQLiteStudio, so only you can exploit it, if you wish so :)

Ad 3) To learn which SQLite is being used you need to know how DLL resolving works in Windows. It's a big topic, but for now it's basically enough to know, that SQLiteStudio under Windows will use sqlite3.dll that is shipped together with it and the file is located in SQLiteStudio's installation directory ("C:\Program Files\SQLiteStudio" by default).

To learn what is the version of SQLite used by SQLiteStudio you can either go to menu Help -> About -> Licenses, or alternatively open SQL Editor window and execute: select sqlite_version()

**Comment by rrandor1** [comment]
What about the Mac environment?

Roger Barr
www.canhealyourself.com

in San Miguel de Allende, Mexico
Cell: (+52) (1) 222 739 8334 (voice & text)
USA: (+1) 510 480 1070 (voice & text)
Skype: rrandor, 
or FaceTime: roger@canhealyourself.com
 

On April 5, 2019 at 12:29:17, Paweł Salawa (notifications@github.com) wrote:

Ad 1) The warning you're seeing is quite common and it means that the executable is not signed by Microsoft's (paid annualy) certificate. You can just uncheck "show this warning every time when I run this application" at the bottom of the warning dialog and you will no longer be bothered with this.

Ad 2) As for the Magellan bug - there is nothing to worry about in case of applications like SQLiteStudio. This application is designed to execute whatever SQL you wish to, but it executes only user's input. It's not internet browser, it's not running code from remote hosts. It's a local application, therefore there is no risk of someone exploiting this bug.

The bug relates only to browsers (such as Chromium/Chrome) or to Android, because millions of applications can use SQLite in Android and some may be malicious.

In case of SQLiteStudio only you, the user of the application can execute SQL in the SQLite used by SQLiteStudio, so only you can exploit it, if you wish so :)

Ad 3) To learn which SQLite is being used you need to know how DLL resolving works in Windows. It's a big topic, but for now it's basically enough to know, that SQLiteStudio under Windows will use sqlite3.dll that is shipped together with it and the file is located in SQLiteStudio's installation directory ("C:\Program Files\SQLiteStudio" by default).

To learn what is the version of SQLite used by SQLiteStudio you can either go to menu Help -> About -> Licenses, or alternatively open SQL Editor window and execute: select sqlite_version()

**Comment by pawelsalawa** [comment]
Similar situation - also a certificate to be renewed (paid) every year.

If you double-click and it shows this dialog, but may be unable to run the app, but then you can (instead of double clicking) right-click on the app icon and select "Run" - in that case the same dialog will appear, but this time you will have option to override and run anyway.

I also think (if I remember correctly at the moment) that under Mac this shows only once and after you overriden it, it won't appear anymore.
