### ISSUE TITLE
Studio doesn't reconnect to the database after closing and reopening it

### ISSUE THREAD

**Issue by quantuumsnot** [pawelsalawa/sqlitestudio#3545]
### Details
The studio is not connected to the database (SQLite 3) after closing it while db connection is still active and tab is still opened. The database/remember tab become active when the user clicks on the database pane. Probably this is a normal behavior - incorporating a defense against people with fast fingers accidentally deleting important data ...

### Steps to reproduce
Connect to a database and select some table, wait for the tab to open and close the studio with [X] window button

### Operating system
Windows 8.1 x64

### SQLiteStudio version
3.2.1
![sqlite321dbnotactiveafterclose](https://user-images.githubusercontent.com/12394810/61384752-e2437a80-a8b9-11e9-9ce1-205019caf89f.png)

**Comment by pawelsalawa** [comment]
The sole fact that "connect/disconnect' icons are grayed out does not mean the connection is not there. Icons become updated if you select datatabse to which you would like to connect or disconnect. How otherwise would SQLiteStudio know which database you would like to connect/disconnect to? You have to select it first. Without selection no connection/disconnection can be performed.

You mentioned earlier on the other issue, that until you double-click on DB, you cannot read or write data to that open table. Is that right? What exactly happens when you click on "Data" tab? Does it show the data, or do you get an error?

**Comment by quantuumsnot** [comment]
It shows, that's why I'm asking if this is the normal behavior?

**Comment by pawelsalawa** [comment]
Yes, as I described above - everything is as expected.
