### ISSUE TITLE
Cannot open db files with SQLiteStudio

### ISSUE THREAD

**Issue by saudiqbal** [pawelsalawa/sqlitestudio#3579]
New install on Windows 10, double clicking on db files gives me error. Can someone confirm this bug for me?

**Comment by pawelsalawa** [comment]
What does the error say?

**Comment by saudiqbal** [comment]
![2019-09-15 18-49](https://user-images.githubusercontent.com/6971514/64928683-a8bfba80-d7e9-11e9-8911-e0004d8b5eaa.png)

**Comment by saudiqbal** [comment]
Also try to check file extension with FileTypesMan and there is a slash error I think

![2019-09-15 18-52](https://user-images.githubusercontent.com/6971514/64928716-22f03f00-d7ea-11e9-8a13-fcc9158cf647.png)

**Comment by pawelsalawa** [comment]
The path you mentioned is only for file icon and actually this one is okay. It's okay to use slash instead of backslash.

The actual problem, a root cause of the problem lies somewhere else. The installator failed to associate proper application path (for execution, not for icon) for the file type. This is a bug and needs to be fixed.

**Comment by pawelsalawa** [comment]
Because installer packages are no longer to be provided (#3626) (only portable archives will be provided), this issue is no longer relevant.
