### ISSUE TITLE
[BUG] Installer: Wrong registry value

### ISSUE THREAD

**Issue by un-pogaz** [pawelsalawa/sqlitestudio#3595]
The Windows installer writes incorrect values to the registry, preventing a DB SQlite file from opening.

The "HKCR\SQLiteStudio.db\shell\Open\Command" value uses a slash (and not a backslash) in the exe path: Executable file not found.

This same value uses single quotes ' instead of a double quotes " around the variable %1: DB file not loaded.

These errors are present in the other registry entries of SQLiteStudio.

Strangely, the slash does not interfere with the "HKCR\SQLiteStudio.db\DefaultIcon" value (Meh, Windows...)

#### Operating system
Windows 7, Windows 10

**Comment by AlexVallat** [comment]
Also, if the path to SQLiteStudio.exe has spaces in, that needs to be quoted too. So instead of 
`C:\Program Files\SQLiteStudio/SQLiteStudio.exe '%1'`
it should be
`"C:\Program Files\SQLiteStudio\SQLiteStudio.exe" "%1"`
or even
`"%ProgramFiles%\SQLiteStudio\SQLiteStudio.exe" "%1"` (but then the type has to be REG_EXPAND_SZ, not REG_SZ)

**Comment by pawelsalawa** [comment]
Superseded with #3725
