### ISSUE TITLE
Update the sqlite3 version inside studio

### ISSUE THREAD

**Issue by tonywang531** [pawelsalawa/sqlitestudio#3607]
### Details
It has been roughly 1 year since this application has been updated.  Is there any plan for update? The SQlite version this studio uses has remained. 3.24.0. The latest version is now 3.30.1. There are some features I would like to use which comes with the new version. 

I have tried to replace the  sqlite3.dll directly, however this results in application error and the program will not start. 

### Steps to reproduce
This is the current state

### SQLiteStudio version
v3.2.1

**Comment by pawelsalawa** [comment]
Yes, update is planned, but due to private situation my time on this project is very limited. I do some work occasionally, but not as much as I used to. I still plan to get back to full speed in some time.

Anyway, I know about new features of new SQLite releases and there are according items in github Issues to track them.

Cheers!
