### ISSUE TITLE
Error executing SQL window function

### ISSUE THREAD

**Issue by kenchock** [pawelsalawa/sqlitestudio#3635]
### Details
Error occurs when running window function.` [08:20:12] Error while executing SQL query on database 'core': near "(": syntax error`

### Steps to reproduce
Execute the following code in a SQL window:
```
with ten as (
	select 1 as t 
	union all 
	select t + 1 
	from ten 
	where t < 10
	),
   ten_w as (
   select t1.t,
   row_number() over (partition by null order by t1.t) as incr
   from ten t1
   )
   select * from ten_w;

```
### Operating system
Windows

### SQLiteStudio version
SQLiteStudio v3.2.1 from https://github.com/pawelsalawa/sqlitestudio/releases/download/3.2.1/SQLiteStudio-3.2.1.zip

**Comment by pawelsalawa** [comment]
It's because window functions are not yet supported in SQLite version that is shipped with SQLiteStudio binary.

You can manually replace the sqlite3.dll in installed SQLiteStudio with one downloaded from sqlite.org and it will work.

There is an issue reported to address this: https://github.com/pawelsalawa/sqlitestudio/issues/3471
