### ISSUE TITLE
Manual Insert (button missing on data grid and form view ?

### ISSUE THREAD

**Issue by DingBEN** [pawelsalawa/sqlitestudio#3636]
### Details
- pressing the insert key on keyboard also fails
- used to be able to do that without issues (is there a setting that would make the table read only in the visual interface?)

### Steps to reproduce
have downloaded anew and installed anew... still cannot open a new row in the data grid... functionality gone!

### Operating system
WIN7 Pro

### SQLiteStudio version
3.2.1 just installed in 3 week of Jan 2020

**Comment by pawelsalawa** [comment]
Well, if the grid is read-only (or just certain columns or rows are), you would see a warning message in the bottom panel, stating why it's read-only.

Another reason that comes to my mind is that your entire database is open in read-only mode (due to missing write permissions on the file/directory), in which case you should not be able to do any other modifications to the database (so you can easily test this by creating some test table) and also during opening such db there should also be a warning about it, if I remember correctly.

Otherwise it should work.

Try creating brand new, empty database, create table and add some rows. Then try pasting. Does that work?

**Comment by DingBEN** [comment]
Hmmm, creating a new database with one table one column, I can hit the Insert key at will and open new rows but it eventually fails after disconnecting/reconnecting the database or leaving studio and restarting
The issue exists with only one db in the database panel
Adding dbs and playing with this resulted in what you see in the attachment.

![DI studio insert](https://user-images.githubusercontent.com/20358705/72814889-d1424000-3c33-11ea-8bb6-4e1881d6ab51.png)

**Comment by pawelsalawa** [comment]
These ampersands are harmless. I mean they should be there and it's a bug, but it's harmless. It's just something that shouldn't be printed in there, but it has nothing to do with your problem.

What you described is really, really weird. Additionally - you're the only person that reports such issue.

What if you keep adding rows using the plus button on toolbar, instead of insert key?

**Comment by DingBEN** [comment]
1. ampersands were only mentioned as encountered to help you cleanup
yes, I know they """should""" be harmless, I am programmer... & ;)

2. Avast:
yes I see it as weird as well, I just installed Avast and did a cleanup... perhaps it zapped a module!? ...but why when I added the new DB, it let me add rows as normal, and then died again!?
I have file and behavior monitoring on Avast disabled. 

3. As mentioned on original post in this thread, button is no longer on screen, even after a reinstall, which lets me suspect the config is the problem...  but on a new clean reinstall on top of the old one, should that not reset the config to install level? how does the install behave?

**Comment by DingBEN** [comment]
When creating objects in the database, the system always shows the SQL in a dialog and waits for a confirmation... when creating new DB ... nothing!? is this by design!?

**Comment by DingBEN** [comment]
new thing I see, when adding a row via SQL(SQL Editor window) it presents the Results/DataGrid panel but no record in window showing until I execute an SQL Editor SELECT clause... I thought it always refreshed the panel with the new record... added a second row via SQL and though the table as rows in it, result is blank until I execute a SELECT !?

**Comment by DingBEN** [comment]
ok ...
- uninstalled SQLiteStudio (it left all the registry keys behind)
- removed anything in registry that had the word SQLiteStudio
- deleted the download\SQLiteStudio folder
- moved my test DBs to an obscure location
...about to download and install again, fresh and test with new everything, vanilla config.
if that works, we have some success, but do not know why this is happening
 then I will point to the obscure location to see if original test DB works
if fails, then I will know that more than likely the engine corrupts the DB somehow,via config or other scenario.
we shal know in a few minutes...

**Comment by DingBEN** [comment]
well a few minutes turn into hours...

![NEW vanilla SQLiteStudio sees magically](https://user-images.githubusercontent.com/20358705/72872915-76a0f680-3cbc-11ea-8dc6-13a3e98d28f0.png)

**Comment by DingBEN** [comment]
**ONE CLUE(again)**: my color scheme(edited configuration) SURVIVED the complete NEW install I described above(how in the H...!) that tends to lead to the thinking that this INSERT issue is tied to the config! ...and the config is stored in the DB.

**ALSO: (separate stuff)**
As I use this tool, I experience it, may as well speak of it, it might be of help.

The consistent layout of buttons across all features is great, but when one is clickdyclickin' working fast, the existing approach is cumbersome in  _**some**_ parts.

The 'Add database' is a tripping obstacle, one can click the wrong button and realize it now says save instead of open ...
When DBs are in various folders... this is NO help, only confusion. Keep it simple, and obstacle free

It allows to type a  name in the dialog with a later BLANK prompt to name the database !? !?
hahaaa! what was I trying? o! I need to read all the signs at the crossroads!? too many signs!
Someone blows the horn behind me, he is a local and knows his way.

No offense meant but I have seen this all my life in programming, process flow even if a bit slower needs to be programmed as road signs... TOO many signs(options) at a node and you get wrecks!

When one uses a tool daily, heavily, one learns all the idiosyncrasies and can flow with that.
When one uses dozens of apps, one forgets exactly how something is EXACTLY structured and must slow the vehicle down to make sure not to bump into things!

...may be much better to have these as 2 separate options
[Create] database
[Load] database (existing)
[Connect] database (once created, connect it automatically, error if fails)
 - existing button to test connection is another obstacle, it always connects!!! the above takes care of it all AND the connect disconnect are in the context menu... too much redundancy.
[Disconnect] database (self-explanatory)

Database names in database panel should visually show which is being addressed (the select options drop down is often off the screen, useless - can be removed)
RED: not connected/problem, ORANGE(Yellow) connected/not current, GREEN loaded/connected/current

Note: as I test, when I rightclick a blank panel data grid view... SQLiteStudio blows up every time

**Comment by pawelsalawa** [comment]
If "+" buttons are not present, then you either use SQL Editor or View window.
Double-click on a table (in database list), it will open Table window. Switch to "Data" tab. There the "+" and "-" buttons must be present.

I don't know about Avast, but antiviruses are unpredictible. Unfortunately. I cannot tell what it did or did not.

Creating DB does not show DDL, because there is no DDL involved. It just creates empty file. There is nothing to execute. DDL is executed only when you modify schema of the DB. So yes, this is by design.

SQL Editor refreshes dataview always when you (re)execute the query. Never automatically. This is intentional and won't be changed, because some people need to keep the "old" data result for reference and they query new results in a separate window. Also, this is natural way. You execute query to read data. It's as simple as that. It's not a continuous real-time data monitor (although I was considering such feature as a separate function in the application, in future).

Finally, I'm pretty sure you're using SQL Editor to query data from tables and you're wondering why there is no "+" button. Well, it's because SQL Editor is not intended for inserting new data. Imagine if you had complex query, with subqueries, comples inter-table joins, expression functions in result columns - how would you insert new row then? To which table and how would it be inserted?

This is why new data for a table should be added/edited/deleted from Table window (double click on a table in databases list). Alternatively - when you have the SELECT query already typed in your SQL editor, you can hold Ctrl key, so the table name (after FROM clause) will get underlined and you can click it to open Table window for it.

**Comment by pawelsalawa** [comment]
The color scheme and all configuration (like database list) survived your reinstallation, because configuration is kept in %APPDATA%\sqlitestudio

**Comment by pawelsalawa** [comment]
Thanks for all suggestions. Let me address & explain few:

> but when one is clickdyclickin' working fast, the existing approach is cumbersome in some parts.
I didn't get what you mean by this.

> The 'Add database' is a tripping obstacle, one can click the wrong button and realize it now says save instead of open
Yeah, I'm also aware of it being not ideal. Your suggestion with separating it into 2 looks promising at first, but then again - how is having 2 buttons on a toolbar/menu different from having 2 buttons in DB dialog window? We're just moving the same problem a level up.

Few years back (when SQLiteStudio was implemented in Tcl/Tk) there was just 1 button to open or create (no matter which one you wanted) database. With C++/Qt I need to use OS native file dialogs, which do not allow mixing these 2 modes. Unfortunately.

> I need to read all the signs at the crossroads!? too many signs!
Signs are there only if you filled form incorrectly (and in some rare cases they also provide some additional information). Would you prefer a popup dialog with error message when you hit "Ok"? Having validation error indicators is basically a standard these days all across the web and it's widely appreciated.

> existing button to test connection is another obstacle, it always connects
Not always. There are various cases when it may fail. The most simple example is when you choose password-protected database. But it's not limited to that. You may have corrupted database (and now know about it yet). You may have reading permissions issue. And so on...

> Database names in database panel should visually show which is being addressed
That's good idea and I considered it already. Just created #3638 for it.

> (the select options drop down is often off the screen, useless - can be removed)
Why do you keep it off the screen? Don't. It's part of a window. It contains information and options. You're missing stuff.



> when I rightclick a blank panel data grid view... SQLiteStudio blows up every time
See #3565

**Comment by DingBEN** [comment]
...ooooo! this saved the day, no wonder it made no sense LOL!
**visual INSERT Issue is resolved. t.y.**

**GO-AROUND** _- no longer needed_
I had come up with a go-around by
- using an INSERT query that created a row of NULLs
- SELECT query which brought similar rows only, including the NULL row at bottom
- Then I could copy/paste a row above and type over the data where needed.

**Glad I do not have to go another tool**
Evaluating other competitive tools of the same, that I had quickly discarded, I chose to spend time on SQLiteStudio since it was the better tool on first trial.
The fact that you answered quickly and even after a short confusion and a quick back and forth, you were able to see my dilemma from the blind side, makes it that I now feel I will continue to evaluate this tool and make it my tool of choice.

I see some misunderstandings in the rest of your answer... will send separate msg to clear it up.
Suffice to stop here for now, INSERT issue is resolved.

thank you much.

**Comment by DingBEN** [comment]
I am closing this issue - the current answer is to double-click a table and select the data tab for a grid view and use the + button or Insert key on the keyboard.
t.y.

**Comment by DingBEN** [comment]
I am reopening this issue so other users who fall in the same trap can see it.
I don't see another way that would accomplish the same.

**Comment by pawelsalawa** [comment]
Even issue is closed, it's still visible and can be found through google.
