### ISSUE TITLE
Query Tab script execution fails to run entire script

### ISSUE THREAD

**Issue by omnigodepot** [pawelsalawa/sqlitestudio#3651]
### Steps to reproduce
Enter the following script in the Query Tab
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Junk;
CREATE TABLE Junk (
    "Id" INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Name" VARCHR(10)
);
COMMIT TRANSACTION;
--|Cursor|

Click [>] Execute Query 
Results: The statement COMMIT TRANSACTION; becomes highlighted...and is the only statement executed.

### Work-Around
Highlight the entire contents of the Query Tab using Ctrl-A, then Click [>] Execute Query.
Results: The entire script is executed correctly.

### Operating system
Windows 10

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment]
This is by design.

Only a single query is executed and it's the one under (or closest to) the cursor. If you want to execute something else, or more - you should highlight what you want to execute. This is common behavior among other tools for databases.

Having that said, you can change this behavior, so it will always execute all queries that are present in the editor. There is an option for that in configuration dialog, at first page of that dialog. See the checkbox at the picture below:
![image](https://user-images.githubusercontent.com/481846/73473389-f6018a80-438c-11ea-8535-01a880a17405.png)

**Comment by omnigodepot** [comment]
Thanks for the detailed response.  I'm new to this tool. Sorry for the false bug report.

Dan Arnold

________________________________
