### ISSUE TITLE
Support for SQLite 3.31

### ISSUE THREAD

**Issue by piula** [pawelsalawa/sqlitestudio#3713]
### Details
SQLite Studio don't handle generated/stored columns introduced with SQLite 3.31.

### Steps to reproduce
Database files using generated columns (see: https://www.sqlite.org/gencol.html) can't be opened with SQLite Studio. Replacing sqlite3.dll with a newer version causes a program crash when opening a table using generated columns.

### Operating system
Windows 10 1809.

### SQLiteStudio version
3.2.1.

**Comment by pawelsalawa** [comment]
Yes. SQLiteStudio fall a little bit behind of SQLite recent features.

Good news is that I'm very actively working on setting up GitHub actions for all 3 platforms for SQLiteStudio. Then I will prepare automated script (or GitHub actions again) to upgrade all SQLite sourcecode (l variations of it = SQLite, SQLCipher, WxSqlite3, System.Data.Sqlite).

Once I have that covered it will be much, much easier to follow new SQLite releases and to deploy new SQLiteStudio releases, which - in the end - means, less overhead on releasing, more time spent on actual features/bugs.

I also decided to remove installers and automated updates (it will still notify user about new version, but it will just give a link to page to download, so user will download and install new version). This (automated updater) has always been a pitfall of new releases and I decided to simplify it.

This removes the major impediment for me to work on the project, because I was always getting demotivated when I thought about process of releasing binaries on all 3 platforms. In result, work on the project should get back on track soon and users may expect more bugs fixed & features implemented.

**Comment by piula** [comment]
Please apologize, I didn't mean to offend you. I apprecaite SQLite Studio very much, it's simply the best tool for SQLite. And it is clear that you are behind SQLite's development. My intention was just to draw your attention to this issue. Imho, it's no problem if some features ain't supported as long as SQLite Studio is continue to work in "compatibility mode" (just ignoring features). But in this case, it's a blocker, unfortunately.

**Comment by pawelsalawa** [comment]
I wasn't offended. Not at all.
I agree, compatibility should be there at first.

**Comment by pawelsalawa** [comment]
Related to #3470

**Comment by pawelsalawa** [comment]
This is fixed now in current master branch.
