### ISSUE TITLE
Encryption support for SQLite >= 3.32.0 and more ciphers

### ISSUE THREAD

**Issue by lke-v** [pawelsalawa/sqlitestudio#3862]
As you may be aware of, support for encryption extensions seems to have changed substantially in SQLite 3.32.0. The author of WxSqlite3 gives a good summary [here](https://github.com/utelle/SQLite3MultipleCiphers#sqlite3multipleciphers).

I could not find any information what encryption/cipher the WxSqlite plugin uses: AES128, AES256? It seems it is not the Chacha20 cipher being default in WxSqlite3 since 4.0.0.
Currently, opening databases encrypted using wxSqlite3 4.0.x or sqleet (no plugin, uses Chacha20, too) is not possible in SqliteStudio.

Please consider providing a plugin using the aformentioned successor of wxSqlite3, [Sqlite3MultiCipers](https://github.com/utelle/SQLite3MultipleCiphers).

**Comment by utelle** [comment]
> I could not find any information what encryption/cipher the WxSqlite plugin uses: AES128, AES256? It seems it is not the Chacha20 cipher being default in WxSqlite3 since 4.0.0.

Right. However, the build file `DbSqliteWx.pro` in the plugin subfolder tells you that the cipher `AES256` is selected as the default cipher.

> Currently, opening databases encrypted using wxSqlite3 4.0.x or sqleet (no plugin, uses Chacha20, too) is not possible in SqliteStudio.

... and that's a pity, because in principal the wxSQLite3 plugin holds all necessary code to support various database types even cross platform:

- Standard SQLite3 (unencrypted)
- wxSQLite3 AES-128 (encrypted)
- wxSQLite3 AES-256 (encrypted)
- ChaCha20-Poly1305 / sqleet (encrypted)
- SQLCipher formats 1 to 4 (encrypted)
- System.Data.SQLite (RC4) (encrypted)

However, it would require a dedicated configuration dialog to be able to select the cipher scheme on connecting to a database file.

**Comment by pawelsalawa** [comment]
Superseeded by #3954
