### ISSUE TITLE
Please consider dropping the 'lib' prefix from the plugin dynamic objects because 'lib' prefix is used for shared libraries

### ISSUE THREAD

**Issue by yurivict** [pawelsalawa/sqlitestudio#3988]
### Details
Shared libraries are registered by ```ldconfig``` and plugins aren't. Shared libraries usually have ```lib``` prefix and plugins don't.

The FreeBSD ports framework warns about sqlite studio plugins:
```
WARN: /usr/ports/databases/sqlitestudio/pkg-plist: [24]: installing shared libraries, please define USE_LDCONFIG as appropriate
```
because they have ```lib``` prefix.

Please consider dropping the ```lib``` prefix.

Thank you,
Yuri (maintainer of the FreeBSD port ```databases/sqlitestudio```).

**Comment by pawelsalawa** [comment]
Hi Yuri, nice to hear from you even after this long time!

One one side it makes sense to distinguish plugins from libraries this way, but on the other side Qt's plugins also come with the `lib` prefix:
```
platforms/libqxcb.so
imageformats/libqgif.so
imageformats/libqicns.so
imageformats/libqico.so
imageformats/libqjpeg.so
imageformats/libqsvg.so
imageformats/libqtga.so
imageformats/libqtiff.so
iconengines/libqsvgicon.so
printsupport/libcupsprintersupport.so
platformthemes/libqgtk3.so
```
They are named this way, because plugins are - well - shared libraries, that just happen to be useful for only one application, but there is nothing stopping other applications from loading them.

Having that said, it is perfectly fine to rename plugin files - both SQLiteStudio plugins and even Qt plugins - as long as they maintain their directory placement and `.so` extension. Both Qt and SQLiteStudio look for their plugins in particular directories by scanning for all `*.so` files, trying to load them and then looking for what they are.

If FreeBSD has preference on this, you could enhance your build scripts to rename them.

Would it be fine for you?

**Comment by yurivict** [comment]
> Would it be fine for you?

Okay, I will see what I can do.

Thank you!

**Comment by pawelsalawa** [comment]
@yurivict Since you're working on the package, please pay attention to the significant recent change - the SQLite library is no longer dynamically linked, but instead SQLiteStudio has its own SQLite bound with the source code and compiled into the binary. Trying to link it dynamically with another libsqlite3* will cause rather bad things (most likely a segfault or somethign like that).
