### ISSUE TITLE
Group-Concat fields not visible in form view

### ISSUE THREAD

**Issue by balajiramanathan** [pawelsalawa/sqlitestudio#4039]
### Details
If a group-concat field is long, it does not appear in form view.  This bug may be related to bug #3764 that was previously reported.  Now, even the text group_concat() does not appear, the field just becomes completely blank.  Switching back to grid view leaves the field blank.

### Steps to reproduce
Create a field through group-concat that contains lots of characters (100 may be the limiting length).  The text appears fine in grid view, but when switching to form view, the text in the field disappears completely.

### Operating system
Windows 7

### SQLiteStudio version
3.34.1

**Comment by balajiramanathan** [comment]
OK, this bug seems to get more complicated the more I dig into it.  Sometimes, instead of showing up blank, the form view shows the wrong values.  For example, if I have 1500 rows in my table and I have set the options to show 1000 rows at a time, then once I go to the second page of results in grid view (rows 1001 through 1500), the grid view shows the correct results for the group-concat field, but if I switch to form view, it shows the values from row 1 for row 1001, from row 2 for row 1002, etc.  It looks like the page number is not taken into account when showing results in form view.

Form view and group_concat are not playing together well, and a complete code review of this functionality is likely required to catch and fix all the bugs in this functionality.

**Comment by balajiramanathan** [comment]
Also, if I click on the three dots (ellipsis) or two blue arrows in grid view, in a text field that is created using a group_concat, the field just becomes blank.  This may be related to why these fields become blank when switching from grid view to form view.

**Comment by pawelsalawa** [comment]
Yes, basically all you observe is one bug manifesting itself in few different ways.

The bug is that when there is more than (or equal to) 100 characters in the cell and the cell is result of some complex expression (I'm yet to check what exactly causes problem here), then loading full value does not work and returns empty value, instead of the full value.

Loading full value happens in several cases:
- when you click "blue arrows"
- when you switch to form view
- when you enter editing mode of the cell (through Enter or double-click)
- when you copy value (through Ctrl+c / Cmd+c)

**Comment by pawelsalawa** [comment]
It turns out that the very same bug caused issue #4035, which is fixed now.
