### ISSUE TITLE
Feature request: Virtual tables and Full-text search 

### ISSUE THREAD

**Issue by TimurMedzhitov** [pawelsalawa/sqlitestudio#4097]
### Details
Support for the full-text search (FTS5).
Currently, a user can not create a virtual table using SQLiteStudio or run queries against virtual tables.
Thanks

**Comment by pawelsalawa** [comment]
Which SQLiteStudio version are you using? In the latest (3.3.3) this works fine: `CREATE VIRTUAL TABLE email USING fts5(sender, title, body);`

**Comment by pl77** [comment]
I've always been able to run queries against FTS5 in SqliteStudio, even 3.2.1.  Odd that you weren't able to.  

It's possible that I had to generate the FTS tables on the sqlite3 CLI, now that I think about it.  I usually use the CLI for large operations like that anyway because it's generally more stable.
