### ISSUE TITLE
Access key is not supported and exposed in the toolbar buttons

### ISSUE THREAD

**Issue by yfdyh000** [pawelsalawa/sqlitestudio#4261]
### Details
Looks the some toolbar buttons are copied from the main menus, but the access key of labels is not supported. This applies to all languages.

<s>Tip: Replace the `&` character with program directly to remove it will cause problems, like the Chinese translation use the `(&E)` form.</s>

https://github.com/pawelsalawa/sqlitestudio/blob/a8c48fd5ee60cbdaa457d34a168cca5da4ad7c3b/SQLiteStudio3/guiSQLiteStudio/mainwindow.cpp#L263
At the same time, other access keys are ineffective on the toolbar buttons.

### Steps to reproduce
Mouse hover to the toolbar buttons.

![SQLiteStudio](https://user-images.githubusercontent.com/1769875/139425528-dee07693-2a67-4d54-ba52-ed4bac575fce.png)
![SQLiteStudio](https://user-images.githubusercontent.com/1769875/139425531-70f1fd23-2b25-484d-b6e5-bc32596af49f.png)
![SQLiteStudio](https://user-images.githubusercontent.com/1769875/139425533-457bfb92-1fcf-492c-95c0-1c538538c9e7.png)
![SQLiteStudio](https://user-images.githubusercontent.com/1769875/139425536-bcefe87e-d068-4957-8e84-a52311fbfbeb.png)

### Operating system
Win10.

### SQLiteStudio version
3.3.3

**Comment by yfdyh000** [comment]
This patch is incomplete repair for Chinese, as I mentioned the `(&E)` in Chinese, now they are useless access key identifiers `(E)` inherit from translation. Further replace or provide the separate strings?

**Comment by pawelsalawa** [comment]
I'm not sure I understand. The fix in #4218 removes the `&` from tooltips of the toolbar. They remain in menubar (as they should).

How is it wrong for Chinese?

**Comment by yfdyh000** [comment]
> I'm not sure I understand. The fix in #4218 removes the `&` from tooltips of the toolbar. They remain in menubar (as they should).
> 
> How is it wrong for Chinese?

The `&Add a database` translated to `添加数据库(&A)` in Chinese, this is a convention because there is no letters in Chinese translation.
The `Add a database` transform to `添加数据库(A)` in Chinese, this is a misleading tooltip, although there is no serious impact.

**Comment by pawelsalawa** [comment]
I'm not sure if it's correct to translate it this way (to put `&A` in addition to a translated string).
Usually the translated string contains the `&` for a letter that fits for the translation language. For example the English text `&Remove the database` is translated to Polish as `U&suń bazę danych` - so the translation uses different acceleration key, that suits the translation. It doesn't have to be the same as original one.

I'm not sure how that plays out for Chinese characters, as I imagine that they are typed using a combination of several keys (is that how it works?), so my recommendation in this case would be to leave the Chinese-translated messages without acceleration keys, because they simply do not have a single key, that works as a acceleration key. Having extra character in parenthesis just for acceleration key doesn't seem to be a sufficient justification for having this extra parenthesis contents. I would rather go with no acceleration key at all.

You may thing - why don't I just fix the code to contain both message versions (with and without ampersands) to use on menu and in toolbar? Well, it's because there is just one `QAction` instance that handles the "Add a database" request and then this `QAction` is being added to both menubar and to toolbar. And there is dozens of such actions. It would not only require to rework all these actions to separate their messages (already a lot of work), but also when adding any new action, a developer would have to remember to do it twice - with and without ampersand. I'm not convinced that retaining acceleration keys in all translations justifies extra maintenance. Are you?

**Comment by yfdyh000** [comment]
> I'm not sure how that plays out for Chinese characters, as I imagine that they are typed using a combination of several keys (is that how it works?), so my recommendation in this case would be to leave the Chinese-translated messages without acceleration keys, because they simply do not have a single key, that works as a acceleration key. Having extra character in parenthesis just for acceleration key doesn't seem to be a sufficient justification for having this extra parenthesis contents. I would rather go with no acceleration key at all.

This is a convention for UI in Chinese, the keyboard operator needs the acceleration keys, and usually in accordance with English. BTW, we use Pinyin IME.

> 
> You may wonder - why don't I just fix the code to contain both message versions (with and without ampersands) to use on menu and in toolbar? Well, it's because there is just one `QAction` instance that handles the "Add a database" request and then this `QAction` is being added to both menubar and to toolbar. And there is dozens of such actions. It would not only require to rework all these actions to separate their messages (already a lot of work), but also when adding any new action, a developer would have to remember to do it twice - with and without ampersand. I'm not convinced that retaining acceleration keys in all translations justifies extra maintenance. Are you?

I understand, but it is indeed a glitch, so reported. Later, I will do a simple fix for Chinese. I hope this is an issue only to Chinese.

I also envisaged, add the access keys to the menus through coding, but this will lose change possibilities from the translation, adding optional translation to access key seems to be more trouble.

**Comment by pawelsalawa** [comment]
Understood. I merged your PR as all of it makes sense.
