### ISSUE TITLE
Languages option show as blank while American English is enabled

### ISSUE THREAD

**Issue by yfdyh000** [pawelsalawa/sqlitestudio#4278]
### Details
In 3.4.0.

### Steps to reproduce
Set language to American English. Restart and check this option in configuration dialog.

### Operating system
Win10.

### SQLiteStudio version
3.4.0  https://github.com/pawelsalawa/sqlitestudio/actions/runs/1385055700

**Comment by pawelsalawa** [comment]
Out of curiosity I digged into this one a little bit already. Leaving some info for myself later to fix it faster:

Preliminary investigation reveals that the problem is that method `getAvailableLanguages()` (in translations.cpp) returns `QMap<QString,QString>` where the key (being language name, like `American English`) gets overwritten, because the `QLocale` returns this language for both `en_us` and `en` locales. Whichever comes later from "*.qm" files listing, that one takes precedense.

Because of that only `en` or `en_us` is in the returned `QMap` and thus it is processed later in `void ConfigDialog::initLangs()` with showing "American English" or blank randomly (depending which qm files come first and which later).
