### ISSUE TITLE
GIS

### ISSUE THREAD

**Issue by PeterSzocs** [pawelsalawa/sqlitestudio#4316]
### Details
Greetings to all,

I tried to add GIS functions to Sqlite Studio using mod_spatialite5.
It seems to work!
I took the idea from here:
[https://github.com/sqlitebrowser/sqlitebrowser/wiki/SpatiaLite-on-Windows](url)
useful links:
[http://www.gaia-gis.it/gaia-sins/](url)
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=Lodable+Modules+in+5.0

Is it possible that Sqlite Studio includes this module by default?

Best regards,
Peter
### Operating system
Win 10

### SQLiteStudio version
3.3.3.

**Comment by pawelsalawa** [comment]
SQLiteStudio supports SQLite extensions pretty well. You can download SpatiaLite put it to SQLiteStudio's directory or any `%PATH%` directory and then add it in SQLiteStudio's "Extensions Manager" window, so it's automatically loaded for all databases that you want upon every startup of SQLiteStudio.

I see no point in adding this extension into the same package as SQLiteStudio, because it's pretty big (8MB compressed) and only small group of SQLiteStudio users would use it.

I believe that only small or general-purpose extensions should be included in the default package. Others should be installed by users when they need it. That's what the "Extensions Manager" is for in SQLiteStudio.
