### ISSUE TITLE
bug: translation is broken on windows

### ISSUE THREAD

**Issue by zeliboba7** [pawelsalawa/sqlitestudio#4385]
### Details
Not all the strings in menu get translation, although they are translated in the source.

### Steps to reproduce
1. Download version 3.3.3 
2. Unpack
3. Run
4. Choose language Russian (of any other)
5. Open menu "Database", "Structure"
6. See untranslated strings like "Add a database", "Refresh all database schemas"

### Operating system
Windows 

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment]
I'm not sure whether the statement _"although they are translated in the source"_ referred to the source code branch of 3.3, or master, cause master branch will always have more translations than the 3.3.

Anyway, with #4433 fixed in master branch, all translations will be reflected from master branch (starting with Monday morning build in the GitHub actions).
