### ISSUE TITLE
Auto word wrapping

### ISSUE THREAD

**Issue by Mickychen00** [pawelsalawa/sqlitestudio#4402]
Is there a settings or function for SQLITE studio to do "Auto word wrapping" in its SQL Editor? Like VS Code and Sublime Text.

**Comment by pawelsalawa** [comment]
Surprisingly therer is not, at the moment. I will keep this post to implement it.

**Comment by schmidtl4** [comment]
+1 and to clarify, it would also be good to be able to turn on auto wrapping in the results Grid View for columns that have long text.  If the auto-wrap feature were on, the rows should expand to a height that would make all text visible (maybe to a max number of rows?) instead of having the blue chevrons at the right to expand the field.
When the blue chevrons ARE present (auto word-wrap off), it would be great if the expanded text would also resize the row it's in so that the entire text was visible (vs. having to manually drag the row "border" at the left to the fully visible height.
