### ISSUE TITLE
Error message: near "AUTOINCREMENT": syntax error

### ISSUE THREAD

**Issue by mudgen** [pawelsalawa/sqlitestudio#4447]
### Details
I tried adding "AUTOINCREMENT" to my existing database table.  

When I try to commit the change I get this error: `[09:54:06] Could not commit table structure. Error message: near "AUTOINCREMENT": syntax error`

This is the SQL that gets generated by sqlitestudio that causes the error:
```
CREATE TABLE records3 (id INTEGER, datetime NUMERIC, PRIMARY KEY (id) AUTOINCREMENT);
```

### Operating system
Linux

### SQLiteStudio version
SQLiteStudio version 3.3.3

**Comment by pawelsalawa** [comment]
SQLiteStudio should not allow you to use `AUTOINCREMENT` with table-level constraint. It should be allowed only for column-level constraint. It's a bug to fix.

Regardless of above, you can still add the primary key with `AUTOINCREMENT`, just just have to edit the `id` column and enable it there, instead of adding table-level constraint.
