### ISSUE TITLE
Values in Result table change after update on source table if shortened text values are displayed 

### ISSUE THREAD

**Issue by phidrho** [pawelsalawa/sqlitestudio#4458]
### Details
If we run select query on table with field that has long text with newlines inside we get result table with shortened text values, and this is OK, but the problem is when source data table gets changed (updated in my case), interaction with Result table is shifted by one row. This can be avoided if manually forced to load full values, but it's not practical. See video for demo: https://youtu.be/qImLw8P-soY

### Steps to reproduce
Run queries on test database:
[test.zip](https://github.com/pawelsalawa/sqlitestudio/files/8831618/test.zip)

```sql
SELECT
    id,
    text,
    count(text) AS number_occurrences,
    (LENGTH(text) - LENGTH(REPLACE(text, CHAR(10), ''))) AS number_of_newlines
    
FROM
    my_table

WHERE
    done_flag IS NULL
    
GROUP BY
    text
    
ORDER BY
    number_occurrences DESC,
    number_of_newlines DESC,
    text ASC
    
LIMIT
    100;
```

```sql
UPDATE
    my_table
SET
    done_flag = 1
WHERE
    text = '';
```

### Operating system
I tested only on Windows 10

### SQLiteStudio version
SQLiteStudio v.3.3.3

**Comment by pawelsalawa** [comment]
I see. The problem is that when copying value from a cell, the "full load" is done transparently for sake of copying. Since you've updated table in the mean time, the query used for "full load" will no longer return same results as it used to when you originally executed the `SELECT` query.

At the moment I'm not sure how to solve it in a good way. The thing is that data values are not loaded fully for initial `SELECT` due to memory optimization reasons. Then copying cell value does execute the same query again, but limits it only to the copied row by its row index from the top. In your case it has already changed, because you updated your table already and order of rows has changed.

For now I think that better compromise would be to resign from memory optimizations entirely, as it causes a lot of troubles (not only this one here). The downside is that some users may experience running out of memory if they query big number of columns with many huge values stored in them, but I guess that's the life...

**Comment by pawelsalawa** [comment]
Closely related to #4240
