### ISSUE TITLE
using dead keys on international keyboard

### ISSUE THREAD

**Issue by Middenraai** [pawelsalawa/sqlitestudio#4545]
### Details
One feature which I dearly miss in SQLiteStudio, and which I was not able to get working thus far, is the possibility to use the 'dead keys' on my US-international keyboard to type a diacritic (like `) followed by a base letter (like a) in order to create a combined character (like à). Especially when typing a long text into a multiline character string/field this would come in handy. Is this somehow possible? The other apps on my pc recognize these combinations automatically. Right now as a workaround I use copy/paste from a separate text file, but this becomes tiring after a while.

**Comment by pawelsalawa** [comment]
Are you using Linux?

**Comment by Middenraai** [comment]
Thanks for your quick reply!

You are right. Perhaps I should have mentioned? I use Ubuntu 20.04 LTS.

------- Original Message -------
Op maandag 7 november 2022 om 22:00 schreef Paweł Salawa ***@***.***>:

**Comment by pawelsalawa** [comment]
As far as I investigated this some time ago, the problem is that Qt, that is shipped with SQLiteStudio does not have some extension needed for the "dead keys". Unfortunately I'm not familiar with this at all and I don't know what needs to be done to enable it for Qt. There are many posts over the internet, that these "dead keys" do not work with Qt for some people, but I also heard from some Linux users, that they use dead keys in other Qt applications, so I don't know how to make it work here...

**Comment by Middenraai** [comment]
Again, thanks for your quick and in-depth response!

Hmmm, from my part I am not familiar with Qt. But understand that they regularly provide updates?
Anyhow, I am happy that this issue is 'on your radar'. With your hints I will experiment further.

------- Original Message -------
Op dinsdag 8 november 2022 om 11:13 schreef Paweł Salawa ***@***.***>:
