### ISSUE TITLE
Refer to Python with a variable or make inclusion more flexible

### ISSUE THREAD

**Issue by onkobu** [pawelsalawa/sqlitestudio#4662]
### Details
Currently .pro-file refers to Python by directly using -Ipython which may or may not exist depending on the target system. Some Linux distributions support even parallel installations of Python incl. a selection mechanism. It'd make life (esp. on Gentoo) much easier if this is expressed through a variable instead that can be overridden during build time. Something like PYTHON3 for INC and LIB is absolutely sufficient. 

In the Gentoo ebuild INCLUDEPATH as well as LIBS would be adjusted to also contain best matching Python variant. So it'd be absolutely feasible if -Ipython is just omitted/ suppressable.

### Steps to reproduce
Try to build 3.4.0+ on a system with Python other than 3.9 or with a selection mechanism for multi-version Python that keeps LD_PATH and others clean.

### Operating system
Recent Gentoo Linux, gcc11, Python 3.10 (and 3.9 and optional 3.8)

### SQLiteStudio version
3.4.0, 3.4.1, 3.4.2

It'd be also great to have simple way of determining whether Python must be exactly 3.9 or >=3.9.

**Comment by pawelsalawa** [comment]
It seems that Python is not very compatible between versions. At least at C API or ABI level. I don't remember details right now, but I remember I struggled with it.

This is why linking is currently done explicitly against `-lpython3.9`. I will keep this issue open in order to improve the plugin compatibility with different Python versions (also in terms of compilation flags), but I need to investigate it first.

**Comment by onkobu** [comment]
So I'm marking this as experimental and to match 3.9 exactly. Thanks a lot.

**Comment by onkobu** [comment]
Now on Gentoo with 3.4.3 and Python >=3.9, compiles successfully with 3.10 and 3.11. Had to patch the .pro-file to exclude -lpython3.9. This is replaced by the build process with the result of the dynamic lookup through LD-environment variable.
