### ISSUE TITLE
SQLiteStudio 3.4.3 - Databases not valid after first start from installer.

### ISSUE THREAD

**Issue by Andreas0707** [pawelsalawa/sqlitestudio#4687]
### Details
Today i installed SQLiteStudio 3.4.3.
After the start from the installer all databases are displayed with (error).
The tooltip info says: Database files are not existing
After the second start everything was normal again.

### Steps to reproduce
Install SQLiteStudio 3.4.3 and start from installer.

### Operating system
Windows 10

### SQLiteStudio version
3.4.3

**Comment by pawelsalawa** [comment]
Are your databases perhaps added with relative file path? In that case the "working directory" will matter and the installer might have started SQLiteStudio with a different working directory than your usual working dir. Would that explain your case?

**Comment by Andreas0707** [comment]
The tooltip shows the full path.
I reproduced it by installing SQLiteStudio again.
The same error occured, see the picture.
<img width="293" alt="SQLiteStudio-Bug1" src="https://user-images.githubusercontent.com/125352954/226727109-65974d9e-dd2e-4540-9e5d-d64742e55162.png">

**Comment by Andreas0707** [comment]
Yes, the path exists and is correct.
But drive E: is a mapped directoy, not a real drive.
As far as i know this mapped drives are only visible to the user, not to the administrator.

**Comment by pawelsalawa** [comment]
Oh, I see. Well, when you run installer as a non-administrator user, it will ask for Administrator password/pin, so it can actually perform installation. From that moment the installer process runs under different user - the administrator. If Administrator cannot see the mapped folder, well, it is what it is and I'm afraid it's not something that can be fixed.

The installer process is only aware of the currently running user (the Administrator) and cannot know what other user should it use to run the SQLiteStudio process.

There is no easy or known way to fix it at the moment, but I guess it's fine, because it affects only the case when you place db files in mapped folders and also you can just not run it directly from the installer, but instead close installer and run the app from the Start menu.
