### ISSUE TITLE
SQLite studio GUI does not appear

### ISSUE THREAD

**Issue by amaru96** [pawelsalawa/sqlitestudio#4881]
### Details
The GUI does not appear after launching the SQLiteStudio.exe. The process is visible and running in task manager but the GUI never appears. Ending the process and relaunching the exe produces the same result - process appears in task manager but GUI doesn't load. I have uninstalled and reinstalled with the same result. Run as administrator, same result.

### Steps to reproduce
Double click SQLiteStudio.exe

### Operating system
Windows 11

### SQLiteStudio version
3.44

**Comment by pawelsalawa** [comment]
Didn't you try to load some huge contents (i.e. SQLite database file) into SQL Editor window? I mean instead of adding the database to list of registered databases, you tried to load it's contents as text into SQL Editor? If so, it probably freezed your SQLiteStudio already at that moment and you killed it, but it probably already managed to store the contents in the session, so now it tries to restore the session every time you run it, freezing all over again.

Anyway, the best you can do now is to rename the config file to a backup name (while the app process is not running) and try again then. Config file location is documented at https://github.com/pawelsalawa/sqlitestudio/wiki/Configuration_directory_location

**Comment by amaru96** [comment]
Thanks for the tip. I deleted my config file and the GUI launched!
