### ISSUE TITLE
Rows affected shows negative number in the status window for large numbers

### ISSUE THREAD

**Issue by hackerceo** [pawelsalawa/sqlitestudio#4882]
### Details
When performing a large query that affects a very large number of rows the status window shows the following: "[16:01:30] Query finished in 8039.805 second(s). Rows affected: -1750869998".  It appears that the number displayed has rolled over on a signed integer whereas in actuality an unsigned integer should be used in this area of the code.

### Steps to reproduce
This should occur with any update that affects a large number of rows that would cause the signed integer used in the display routine to overflow.  In my circumstances the actual number of rows affected was 24,018,933,778.

### Operating system
Windows 11

### SQLiteStudio version
SQLiteStudio v3.4.4

**Comment by pawelsalawa** [comment]
This requires usage of `sqlite3_total_changes64()` SQLite API introduced in SQLite 3.37.0.

SQLiteStudio 3.4.5 (for which this was planned to be fixed in) uses SQLite 3.34 and I don't want to upgrade it in this bugfix version. The newest SQLite will be used in SQLiteStudio 3.5.0, which will also cover features introduced in SQLite versions 3.38 - 3.47 (or whatever version will be newest by the release time). Therefore I postpone this bugfix to SQLiteStudio 3.5.0.
