### ISSUE TITLE
import function too slow

### ISSUE THREAD

**Issue by cmedinga** [pawelsalawa/sqlitestudio#4921]
### Details
I'm importing a csv file of 66.927 records x 34 columns. If I do it with select import function, it takes 1513 seconds. If I do it via Tools > Import menu, it takes less than a second.

### Steps to reproduce
Create a text file of that size (due to sensitive information, I cannot share it) separated by semicolons. Try to import to a new table with this query:

```
SELECT import('c:\path\to\file.csv', 'CSV', 'my_table', 'utf-8', 'CsvImport.FirstRowAsColumns=true CsvImport.Separator=1 
CsvImport.NullValues=true');
```
With the import window, use this params:
![image](https://github.com/pawelsalawa/sqlitestudio/assets/112566083/bbb39926-dc2a-4bd0-81dd-c7bc27b4bbd1)

### Operating system
Windows 10

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment]
I'm not 100% sure, but if I remember correctly, the options should be specified in a 1-per-line manner, like this:
```
SELECT import('c:\path\to\file.csv', 'CSV', 'my_table', 'utf-8', 'CsvImport.FirstRowAsColumns=true
CsvImport.Separator=1
CsvImport.NullValues=true');
```

Let me know if that makes any difference. If yes, I will add this information to wiki https://github.com/pawelsalawa/sqlitestudio/wiki/CsvImport

**Comment by cmedinga** [comment]
Yes, I tried it, but it makes no difference. It takes more than 20 minutes to load the file.

**Comment by pawelsalawa** [comment]
I've made some tests now (on a virtual machine, which is less performant by default) and for me importing such amount of rows & columns using the Import Dialog takes around 7 seconds, while doing it through `import()` function in SQL query it takes 9 seconds. A bit longer, but definitely nowhere near your results. The difference comes probably from overhead of using `SAVEPOINT` and `RELEASE` in query executor of SQL editor, instead of `BEGIN`/`END` used by the Import Dialog.

As long as I cannot reproduce this problem in such significance as reported (over 20 minutes) I consider this issue to be not valid.
