### ISSUE TITLE
Export the way-it-comes

### ISSUE THREAD

**Issue by CypherPotato** [pawelsalawa/sqlitestudio#4928]
### Details
Copied from https://github.com/pawelsalawa/sqlitestudio/discussions/4927.

I needed to deal with huge tables, with over 20 GB of data, and work on exporting certain columns with queries on them.

For this, the ideal is that, as it reads the lines, it exports the contents of the table to my file, however, I tried to export to CSV, got it exporting, and even after some time, no lines were written to my file.

After canceling the operation, I saw that this was written in the console:

    [15:25:01] An error occured while executing the count(*) query, thus data paging will be disabled. Error details from the database: interrupted

There should be a way to disable this count, because it takes time in very large tables, and this way, write new lines as they were read.

Also an indicator of how many lines have already been written when you are not using the progress calculation, just to show if the export is going well.

**Comment by pawelsalawa** [comment]
Why do/did you use for exporting - the Export Dialog, or `export()` function in a query?

**Comment by pawelsalawa** [comment]
Nevermind. There is no `export()` function. ;)

**Comment by pawelsalawa** [comment]
I have a different question - what SQLiteStudio version was this attempted on? I'm asking, cause according to my tests the row counting is not performed during export, unless the exporting is done to PDF format (currently that's the only output format that requires knowledge about total number of results ahead of actual exporting).

**Comment by CypherPotato** [comment]
Tried on 3.4.4 when trying to export an huge query to an csv file.

**Comment by pawelsalawa** [comment]
I cannot reproduce it. Exporting never calls row counting, unless export is done to to PDF format.

Another case when this message can show up in console is when you execute this query in SQL Editor to see results and you interrupt it. Maybe it was printed already before, when you executed query that you intended to export, but you realized it doesn't make sense to wait for results, but rather already start exporting?

Also, when Exporting is in progress and you interrupt it, all data exported so far should be flushed into the file (they don't show in the file immediately during export, because Qt uses memory buffering when writing files). I was able to interrupt and got part of the exported data in the output file.

As for the progress on exported rows I agree. I will add some counter to UI.
